In [ ]:
import numpy as np

In [ ]:
NN=np.array([[0,1,0],[0,0,1],[1,0,0]])

print(NN)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [ ]:

rows,columns=NN.shape

columns_NA=np.count_nonzero(NN)
#comparar si rows=columnas, sino, error



k=0
NA=np.zeros((rows,columns_NA))
Arches=((1,columns_NA))


for i in range(columns):
  for j in range(rows):
    if NN[i,j]==1:
      NA[i,k]=1
      NA[j,k]=-1

      k+=1
      


print(NA)


TypeError: ignored