In [ ]:
import numpy as np

In [ ]:
NN=np.array([[0,1,0],
             [0,0,1],
             [1,0,0]])

print(NN)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [ ]:

rows,columns=NN.shape

columns_NA=np.count_nonzero(NN)
#comparar si rows=columnas, sino, error


k=0
NA=np.zeros((rows,columns_NA))
arches = ["" for i in range(columns_NA)]

for i in range(columns):
  for j in range(rows):
      if NN[i,j]==1:
        NA[i,k]=1
        NA[j,k]=-1
        if i==0:
          arches[k]="s->"+str(j+1)
        elif j==0:
          arches[k]=str(i+1)+"->s"
        elif i==columns-1:
          arches[k]="t->"+str(j+1)
        elif j==columns-1:
          arches[k]=str(i+1)+"->t"
        else:
          arches[k]=str(i+1)+"->"+str(j+1)
        k+=1

print("Arches = ",arches)
print(NA)


Arches =  ['s->2', '2->t', '3->s']
[[ 1.  0. -1.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]
